### PR TITLE
Issue 12: Broken CSS on Bootswatch settings page

### LINKED ISSUE #12: Broken CSS on Bootswatch settings page
Originally, the Bootswatch settings page for Bootstrap theme showed small thumbnails on wide windows (e.g., 3 thumbnails per row on 1200px windows, fewer on narrower windows), as on, for example, [the main Bootswatch page](https://bootswatch.com). This CSS is broken on Bootstrap Lite and Bootstrap5 Lite, so that there's always only one thumbnail per row, even on large windows, on the "Bootswatch themes" tab of the Bootstrap5 Lite settings page.

A fix for Bootstrap Lite is part of [a pending PR](https://github.com/backdrop-contrib/bootstrap_lite/pull/46). The PR for this issue makes the corresponding changes for Bootstrap5 Lite.

### PR DESCRIPTION
**Pull request by bugfolder**
Fixes https://github.com/backdrop-contrib/bootstrap5_lite/issues/12.

### CODE REVIEW

**Comment by docwilmot** [comment]
I'm getting gaps in the grid of icons. Any idea why?:

bootswatch

**Comment by bugfolder** [comment]
It looks like Sketchy is a few pixels taller, presumably because of the two lines of description. So probably that min-height in the added CSS needs to be a few pixels taller. (There may also be a better way of doing the CSS than what I did; my CSS is pretty shaky.)

**Comment by bugfolder** [comment]
Odd, though; when the display is 3 across, Sketchy should be in the 3rd column. Which Bootstrap CDN are you using?

**Comment by docwilmot** [comment]
5.0.1.

**Comment by bugfolder** [comment]
Weird. I can't reproduce this with the current PR on either Safari or Chrome, but I can get the same effect if I set the min-height down to 40px. So I'm pretty sure that that's what's causing it, and some subtle difference (maybe in font handling?) is  tweaking the overall height to of Sketch (and other themes with two-line descriptions) to slightly more than the min-height.

I'm going to fix the height of that block at 45px, which should ensure that they're all the same height, and any few-pixel differences will just eat up some whitespace.

**Comment by docwilmot** [comment]
OK, that fixes it. We could also use the JS/CSS effect from the layout configure pages, to hide the radios and give a nice hover/selected effect. But that could be future.

**Pull request merged**
