### PR TITLE
Added hook for modifying the webform email element

### PR DESCRIPTION
**Pull request by tkcent**
The email element in webforms does not get the proper bootstrap styling.

### CODE REVIEW

**Comment by docwilmot** [comment]
I dont think it should be the theme's responsibility to provide styling for contrib modules. But not sure. Anyone else have an opinion on this? @stpaultim ?

**Comment by tkcent** [comment]
Hmm...  Maybe its a problem with Webform then.  Not sure why the form-control class isn't getting applied to the email elements.  Am I wrong in thinking the bootstrap5_lite_email() function should apply to webforms well?

**Comment by docwilmot** [comment]
I suspect its because webform isnt using core `'type' => 'email'` field.

**Comment by docwilmot** [comment]
Meh, merged it anyway. Its a small hook, and webform is popular. Its more reasonable for this theme to try and support webform than to expect Webform to change its code to suit.

**Comment by tkcent** [comment]
Thanks!  I was looking into the webform code, and was thinking it might be a big deal.

**Pull request merged**
