### PR TITLE
Issue 16: Bundle Bootstrap

### LINKED ISSUE #16: Bundle Bootstrap
Currently we're loading Bootstrap, Bootswatch and Font Awesome via CDN. We could bundle the files instead.

### LINKED ISSUE #30: How to upgrade CDN to newer version
Just new to Backdrop and the Bootstrap5 Lite theme. Currently Bootstrap5 Lite is configured to go up to version 5.0.1 and the current new version of Bootstrap is 5.3.1 and also the theme supports Font Awesome up to 4.4.0 and the version 6.2.1 of Font Awesome is the new one.  Can the Bootstrap5 Lite be modified to use the newer CDN versions? Can a subtheme be configured to use the newer CDN versions?

### PR DESCRIPTION
**Pull request by bugfolder**
Fixes https://github.com/backdrop-contrib/bootstrap5_lite/issues/16.
Fixes https://github.com/backdrop-contrib/bootstrap5_lite/issues/30.

### CODE REVIEW

**Comment by robertgarrigos** [comment]
~~Reviewed and working as expected :-)~~

**Comment by robertgarrigos** [comment]
However, with this pr I'm having a difference when navbar is set fixed top: header tag in page is missing, as well as admin bar:

Projectes___ERP-2

This is same site without this pr applied:

Projectes___ERP

**Comment by bugfolder** [comment]
@robertgarrigos, I found and fixed a typo in a path. Would you please take another look?

**Comment by robertgarrigos** [comment]
@bugfolder this fixed the problem. thanks!

**Pull request merged**
